FROM ubuntu:12.04
MAINTAINER Javier Domingo Cansino <javierdo1@gmail.com>

RUN ln -s /bin/bash /usr/bin/bash
RUN ln -s /bin/tar /usr/bin/tar
RUN apt-get update 
RUN apt-get install -y libncurses-dev build-essential git subversion zlib1g-dev gawk unzip wget python-setuptools
